#  Items/Parameters that can be reset after the CASPAR engine is started.
#  Like the heatFluor channel, coolFluor channel, PCRA, B, C, and laser PWM
#  Parameters.
#  20220917 weg, started.
#  I think comments are ignored.
#  All pairs are string = string even without double quotes, in fact lose the
#  double quotes.  String to other stuff can be found in string.h but your
#  Friends are: stoi() - to int, stol() - to long int, stod() - double, stof() - float,
#  stoul() - unsigned long, boolean with (astring=="true") using "true" and "false"
#  for the booleans. 
#
[Description]
RecipeVersion = 1
Time = 20220917_1337
Short = "Default settings with PWM enabled"
Long = "SVV is PCR channel XXXX, with PWM enable for laser-nanorod heating"

# Front Qiagen is always Q0, back one is Q1.
# Like the compound Qiagen1_E1D2 but maybe the others, heatFluorChan and heatFluorQiagen are
# easier and clearer.
[Channels]
heatFluor = Qiagen1_E1D2
heatFluorChan = E1D2
heatFluorQiagen = Qiagen1
coolFluor = Qiagen1_E1D2
coolFluorChan = E1D2
coolFluorQiagen = Qiagen0
pcrA = Qiagen0_E1D1
pcrAChan = E1D1
pcrAQiagen = Qiagen0
pcrB = None
pcrBChan = None
pcrBQiagen = None
pcrC = None
pcrCChan = None
pcrCQiagen = None

# Need to disable when not using the laser to avoid the sudo in
# "sudo node caspar.js" .
# Clock should be 19.2e6 divided by Actual Hz (1000) and by Range (1024), 
# usually like 19.2 Mhz / 1024 / 1000 = 19 (an int).
# Range is the number of steps to use within the larger period.
[PWM]
Enable = true
HighRatio = 0.80
LowRatio = 0.001
Clock = 19
Range = 1024
PinNum = 23
Mode = 0


