#  This is the Default recipe file, loaded if you select nothin else on the UI pulldown.
#  Items/Parameters that can be reset after the CASPAR engine is started via the pulldown.
#  Like the heatFluor channel, coolFluor channel, PCRA, B, C, and laser PWM
#  Parameters.
#  20220917 weg, started.
#  Comments are ignored and set off by a hash (#).
#  All pairs are string = string even without double quotes, in fact lose the
#  double quotes.  String to other stuff can be found in string.h but your
#  Friends are: stoi() - to int, stol() - to long int, stod() - double, stof() - float,
#  stoul() - unsigned long, boolean with (astring=="true") using "true" and "false"
#  for the booleans. 
#
[Description]
RecipeVersion = 1
Time = 20221114_1136
Short = "Default settings, SVV and FMDV"
Long = "Pig Seneca Valley Virus and Foot and Mouth Disease Virus test."

# Front Qiagen is always Q1, back one is Q2, with heat in the back.
# Like the compound Qiagen1_E1D2 but maybe the others, heatFluorChan and heatFluorQiagen are
# easier and clearer.
[Channels]
HTP = Q1_E2D2
HTPQiagen = Q1
HTPChannel = E2D2
LTP = Q1_E2D2
LTPQiagen = Q1
LPTChannel = E2D2

pcrA = Q1_E1D1
pcrAQiagen = Q1
pcrAChannel = E1D1
pcrAname = SVV

pcrB = Q2_E1D1
pcrBQiagen = Q2
pcrBChan = E1D1
pcrBname = FMDV

pcrC = Q2_E2D2
pcrCQiagen = Q2
pcrCChan = E2D2
pcrCname = RNaseP

GainCalibration = true
GainHTP = 200.0
GainLTP = 200.0
GainPCRA = 200.0
GainPCRB = 200.0
GainPCRC = 200.0

# Need to disable when not using the laser to avoid the sudo in
# "sudo node caspar.js" .
# Clock should be 19.2e6 divided by Actual Hz (1000) and by Range (1024), 
# usually like 19.2 Mhz / 1024 / 1000 = 19 (an int).
# Range is the number of steps to use within the larger period.
[PWM]
Enable = false
HighRatio = 0.85
LowRatio = 0.0
Clock = 19
Range = 1024
PinNum = 23
Mode = 0

[Cycling]
# Control.cpp L238, thresholds when to switch heat/cool states, or first/second hump.
THRESH = 0.05  # Looked at LV and recipe for CDZ double hump has 0.05 here, 20221026 weg.
THRESHCOOL = 0.135
DTHRESHHEAT = 0.25 # Other version has 0.25, 20220915 weg.
DTHRESHCOOL = 0.8  # Other version has 0.8, ditto weg.

[Recon]
ReconEnable = true
RECON_LENGTH = 600
RECON_TEMP = 55
RECON_WAITTOTEMP = 55
ITER_MAX_PREMELT = 24
AMPL_MIN_PREMELT = 5
CTR_MIN_PREMELT = 5
# casparapi calibrate numbers, L65-102.
FluorCalibPremelt = 150
[RT]
RTEnable = true
RT_LENGTH = 600
RT_TEMP = 60
RT_WAITTOTEMP = 55
ITER_MAX_PREMELT = 24
AMPL_MIN_PREMELT = 5
CTR_MIN_PREMELT = 5
# casparapi calibrate numbers, L65-102.
FluorCalibPremelt = 150

[Fitting]
SMOOTHING = 25
CONVERGENCE_THRESHOLD = 1



