#  Devices' hardware numbers and configurations for the CASPAR01 box.
#  20220905 weg, started.
#  I think comments are ignored.
#  All pairs are string = string even without double quotes, in fact lose the
#  double quotes.  String to other stuff can be found in string.h but your
#  Friends are: stoi() - to int, stol() - to long int, stod() - double, stof() - float,
#  stoul() - unsigned long, boolean with (astring=="true") using "true" and "false"
#  for the booleans. 
#
[Qiagen]
Qiagen0BoardID = ESML10-MB-3021
Qiagen0SerialNo = 0019
Qiagen0SerialPort = /dev/ttyUSB0

Qiagen1BoardID = ESML10-MB-3021
Qiagen1SerialNo = 0018
Qiagen1SerialPort = /dev/ttyUSB1

# Clock should be 19.2e6 divided by Range (1024) and Actual Hz (1000), 
# usually like 19.2 Mhz / 1024 / 1000 = 19 (an int).
[PWM]
HighRatio = 0.90
LowRatio = 0.001
Clock = 19.53
Range = 1024
PinNum = 23
Mode = 0

[ADC]
ADC0Name = QiagenChannelE1D2
ADC0DevID = 0x48
ADC0HighThresh = 0x8000
ADC0LowThresh = 0x7FFF

ADC1Name = Temperatures
ADC1DevID = 0x49
ADC1HighThresh = 0x8000
ADC1LowThresh = 0x7FFF


[USBDAQ]
USBDAQName = DAQ1
USBDAQModel = NI USB-6009
USBDAQSerialNo = 0193FA49

[Box]
BoxName = CASPAR01


