#  Devices' hardware numbers and configurations for the CASPAR01 box.
#  20220905 weg, started.
#  I think comments are ignored.
#  All pairs are string = string even without double quotes, in fact lose the
#  double quotes.  String to other stuff can be found in string.h but your
#  Friends are: stoi() - to int, stol() - to long int, stod() - double, stof() - float,
#  stoul() - unsigned long, boolean with (astring=="true") using "true" and "false"
#  for the booleans. 
#
[Box]
BoxName = CASPAR01

# Qiagen0 is front one, Qiagen1 is the back one, relative to hot air gun.
# Serial ports are the starting ones, if wrong device the code assigns Qiagen0
# and Qiagen1 approriately.
[Qiagen]
Qiagen0BoardID = ESML10-MB-3004
Qiagen0SerialNo = 0015
Qiagen0SerialPort = /dev/ttyUSB0
Qiagen0E1 = 520
Qiagen0E2 = 625
Qiagen0D1 = 570
Qiagen0D2 = 680

Qiagen1BoardID = ESML10-MB-3021
Qiagen1SerialNo = 0016
Qiagen1SerialPort = /dev/ttyUSB1
Qiagen1E1 = 470
Qiagen1E2 = 590
Qiagen1D1 = 520
Qiagen1D2 = 640

# Need to disable when not using the laser to avoid the sudo in
# "sudo node caspar.js" .
# Clock should be 19.2e6 divided by Actual Hz (1000) and by Range (1024), 
# usually like 19.2 Mhz / 1024 / 1000 = 19 (an int).
# Range is the number of steps to use within the larger period.
# NB: PWM also shows up in recipes!  So below are the starting defaults.
[PWM]
Enable = false
HighRatio = 0.80
LowRatio = 0.001
Clock = 19
Range = 1024
PinNum = 23
Mode = 0

[ADC]
ADC0Name = QiagenChannelE1D2
ADC0DevID = 0x48
ADC0HighThresh = 0x8000
ADC0LowThresh = 0x7FFF

ADC1Name = Temperatures
ADC1DevID = 0x49
ADC1HighThresh = 0x8000
ADC1LowThresh = 0x7FFF


[USBDAQ]
USBDAQName = DAQ1
USBDAQModel = NI USB-6009
USBDAQSerialNo = 0193FA49




