#  Devices' hardware numbers and configurations for the CASPAR01 box.
#  20220905 weg, started.
#  I think comments are ignored.
#  All pairs are string = string even without double quotes, in fact lose the
#  double quotes.  String to other stuff can be found in string.h but your
#  Friends are: stoi() - to int, stol() - to long int, stod() - double, stof() - float,
#  stoul() - unsigned long, boolean with (astring=="true") using "true" and "false"
#  for the booleans. 
#
[Box]
BoxName = CASPAR01

# Qiagen1 is front one, Qiagen2 is the back one, relative to hot air gun begin in the back.
# Serial ports are the starting ones, if wrong device the code assigns Qiagen1
# and Qiagen2 approriately.
[Qiagen]
Q1BoardID = ESML10-MB-3004
Q1SerialNo = 0015
Q1SerialPort = /dev/ttyUSB0
Q1E1 = 520
Q1E2 = 625
Q1D1 = 570
Q1D2 = 680

Q2BoardID = ESML10-MB-3021
Q2SerialNo = 0016
Q2SerialPort = /dev/ttyUSB1
Q2E1 = 470
Q2E2 = 590
Q2D1 = 520
Q2D2 = 640

# Need to disable when not using the laser to avoid the sudo in
# "sudo node caspar.js" .
# Clock should be 19.2e6 divided by Actual Hz (1000) and by Range (1024), 
# usually like 19.2 Mhz / 1024 / 1000 = 19 (an int).
# Range is the number of steps to use within the larger period.
# NB: PWM also shows up in recipes!  So below are the starting defaults.
# Enable should be true or false, no caps.
[PWM]
Enable = false
HighRatio = 0.85
LowRatio = 0.0
Clock = 19
Range = 1024
PinNum = 23
Mode = 0

[ADC]
ADC0Name = QiagenChannelE1D2
ADC0DevID = 0x48
ADC0HighThresh = 0x8000
ADC0LowThresh = 0x7FFF

ADC1Name = Temperatures
ADC1DevID = 0x49
ADC1HighThresh = 0x8000
ADC1LowThresh = 0x7FFF

CONVERSION = 0x00
CONFIG = 0x01
LOWTHRESH = 0x02
HITHRESH = 0x03

[GPIO]
HEATER_PIN = 7
FAN_PIN = 4
BOX_FAN = 5
PWM_PIN = 23 
ALERT_PIN = 3  
# Also in the PWM section above.

# Some of the below should be in Assay Recipes too.  So these are defaults.
[MISC]
SMOOTHING = 25
CONVERGENCE_THRESHOLD = 1
RT_LENGTH = 600
RT_TEMP = 60
RT_WAITTOTEMP = 55
RECON_LENGTH = 600
RECON_TEMP = 55
RECON_WAITTOTEMP = 55
CALIBRATION_MIN = 150
# Might want to separate these from MISC into their own section.
ITER_MAX = 24
AMPL_MIN = 10
CTR_MIN = 2
# PREMELT step, both RECON and RT.
ITER_MAX_PREMELT = 24
AMPL_MIN_PREMELT = 5
CTR_MIN_PREMELT = 5
# Control.cpp L238, thresholds when to switch heat/cool states, or first/second hump.
THRESH = 0.05  # Looked at LV and recipe for CDZ double hump has 0.05 here, 20221026 weg.
THRESHCOOL = 0.135
DTHRESHHEAT = 0.25 # Other version has 0.25, 20220915 weg.
DTHRESHCOOL = 0.8  # Other version has 0.8, ditto weg.
# casparapi calibrate numbers, L65-102.
FluorCalibPremelt = 150
FluorCalib = 300
FluorCalibLDNA = 200
