#include <iostream>
#include <wiringPi.h>
#include "caspar.h"

using namespace std;


/* Returns the temperature value for a given fluoresence. Requires the curve generated by heatgen.
 *
 * Args:
 *  temp: The temperature to be compared to the standard curve.
 * 
 * Returns:
 *  Success: Fluoresence for the requested temperature.
 *  Failure: -1. 
 */
double fluorquery(double fluor)
{
    for(int i = 0; i < fluorkey.size(); i++) // For the length of our fluoresence key:
    {
        if(fluorkey[i] > fluor) // If the current value in the key is higher than our target fluoresence:
        {
            return tempkey[i]; // Return the corresponding temperature.
        }
    }
    return -1; // Else, return -1 to indicate failure.
}

/* Returns the fluoresence value for a given temperature. Requires the curve generated by heatgen.
 *
 * Args:
 *  temp: The temperature to be compared to the standard curve.
 * 
 * Returns:
 *  Success: Fluoresence for the requested temperature.
 *  Failure: -1. 
 */
double heatquery(double temp)
{
    for(int i = 0; i < fluorkey.size(); i++) // For the length of our fluoresence key:
    {
        if(tempkey[i] > temp) // If the current value in the key is higher than our target temperature:
        {
            return fluorkey[i]; //Return the corresponding fluoresence.
        }
    }
    return -1; // Else, return a negative 1--temperature out of our keyed range.
}

/* Generates the vector of heats and corresponding fluorescences for waittotemp and holdtemp. Be sure you're using this function with them.
 *
 * Args:
 *  coeff[3]: Coefficients acquired from the GaussNewton3 function.
 *  trigger: A representation of which of the two Gaussians the heater is currently on.

 * Data acquired from a melt test. */
void heatgen(const double coeff[3], bool trigger)
{
    // Declare that we're starting at the beginning of our arrays.
    int startindex = 0;
    if(trigger == true) // On the other hand, if we're on the second gaussian, begin at the dividing index between the two.
    {
        startindex = 74;
    }
    
    // Define our temperatures and z scores for stretching the Gaussian.
    vector<double> temps = {55,55.5,55.83333333,56.16666667,56.5,56.83333333,57.16666667,57.5,57.83333333,58.16666667,58.5,58.83333333,59.16666667,59.5,59.83333333,60.16666667,60.5,60.83333333,61.16666667,61.5,61.83333333,62.16666667,62.5,62.83333333,63.16666667,63.5,63.83333333,64.16666667,64.5,64.83333333,65.16666667,65.5,65.83333333,66.16666667,66.5,66.83333333,67.16666667,67.5,67.83333333,68.16666667,68.5,68.83333333,69.16666667,69.5,69.83333333,70.16666667,70.5,70.83333333,71.16666667,71.5,71.83333333,72.16666667,72.5,72.83333333,73.16666667,73.5,73.83333333,74.16666667,74.5,74.83333333,75.16666667,75.5,75.83333333,76.16666667,76.5,76.83333333,77.16666667,77.5,77.83333333,78.16666667,78.5,78.83333333,79.16666667,79.5,79.83333333,80.16666667,80.5,80.83333333,81.16666667,81.5,81.83333333,82.16666667,82.5,82.83333333,83.16666667,83.5,83.83333333,84.16666667,84.5,84.83333333,85.16666667,85.5,85.83333333,86.16666667,86.5,86.83333333,87.16666667,87.5,87.83333333,88.16666667,88.5,88.83333333,89.16666667,89.5,89.83333333,90.16666667,90.5,90.83333333,91.16666667,91.5,91.83333333,92.16666667,92.5,92.83333333,93.16666667,93.5,93.83333333,94.16666667,94.5,95,95.5,96};
    vector<double> zscores = {-1.615167831,-1.544943143,-1.498126685,-1.451310225,-1.404493766,-1.357677308,-1.310860848,-1.26404439,-1.217227931,-1.170411471,-1.123595013,-1.076778555,-1.029962095,-0.983145636,-0.936329178,-0.889512718,-0.84269626,-0.795879801,-0.749063342,-0.702246883,-0.655430425,-0.608613965,-0.561797507,-0.514981048,-0.468164588,-0.42134813,-0.374531671,-0.327715212,-0.280898753,-0.234082295,-0.187265835,-0.140449377,-0.093632918,-0.046816458,0,0.046816458,0.093632918,0.140449377,0.187265835,0.234082295,0.280898753,0.327715212,0.374531671,0.42134813,0.468164588,0.514981048,0.561797507,0.608613965,0.655430425,0.702246883,0.749063342,0.795879801,0.84269626,0.889512718,0.936329178,0.983145636,1.029962095,1.076778555,1.123595013,1.170411471,1.217227931,1.26404439,1.310860848,1.357677308,1.404493766,1.451310225,1.498126685,1.544943143,1.591759601,1.638576061,1.68539252,1.732208978,1.779025438,1.825841896,-2.283747771,-2.204997846,-2.126247924,-2.047498001,-1.968748077,-1.889998154,-1.811248232,-1.732498307,-1.653748385,-1.574998463,-1.496248538,-1.417498616,-1.338748693,-1.259998769,-1.181248846,-1.102498924,-1.023748999,-0.944999077,-0.866249155,-0.78749923,-0.708749308,-0.629999386,-0.551249461,-0.472499539,-0.393749616,-0.314999692,-0.236249769,-0.157499847,-0.078749922,0,0.078749922,0.157499847,0.236249769,0.314999692,0.393749616,0.472499539,0.551249461,0.629999386,0.708749308,0.78749923,0.866249155,0.944999077,1.023748999,1.102498924,1.181248846,1.299373731,1.417498616,1.5356235};

    // Declare our z score of interest to start at the start of the current gaussian.
    int j = startindex;
    int i = 0;
    while(i < y.size() && j < zscores.size()) // While we're still within our y values and our z scores:
    {
        while((x[i]-coeff[1])/abs(coeff[2]) < zscores[j] && i < y.size()) //While the z score of our current fluoresence is less than the nearest temp z-score and we're inside our y values:
        {
            fluorkey.push_back(y[i]); // Push the y value onto the fluoresence key.
            tempkey.push_back(temps[j]); // Pair it with the lowest temperature with a larger z score..
            i++;
        }
        cout << "Temp " << temps[j] << " complete." << endl; // Provide feedback to the console.
        j++; // Move to the next temperature and z-score pair.
    }
}


/*
 * Holds at temperature for a given period of time. This function also requires heatgen to have populated relevant curves.
 * 
 * Args: 
 *  Temp: temperature to be held at.
 *  Time: Time in seconds to hold.
 */
void holdtemp(double temp, double time)
{
    // Turn the heater on.
    digitalWrite(HEATER_PIN,HIGH);

    // Retrieve our target fluoresence from our heating curves.
    double fluortarget = heatquery(temp);
    while(y[y.size()-1] < fluortarget) // While we're below the temperature of interest, heat:
    {
        delay(10);
    }
    int start = 0;
    double ycurrent;
    cout << "Activate hold." << endl; // Log that we're holding to the console.
    while(start < time * 100)
    {
        ycurrent = y[y.size()-1];
        if (ycurrent < fluortarget - 20) // If our current fluoresence is below the target minus 20:
        {
            digitalWrite(HEATER_PIN, HIGH); // Turn the heater on.
        }
        else if (ycurrent > fluortarget) // If it's above the target:
        {
            digitalWrite(HEATER_PIN, LOW); // Turn the heater off.
        }
        delay(10); // Wait 10 milliseconds before checking again.
        start++; // Increment our wait.
    }
}


/*
 * Waits for the temperature to reach a certain value based on the curve created by heatgen. For the current functionality, it only operates for falling.
 * 
 * Args:
 *  Temp: temperature to fall to.
 */
void waittotemp(double temp)
{
    double fluortarget = heatquery(temp); // Retrieve the target fluoresence from the curves. 
    cout << "Falling." << endl; // Log that we're falling.
    while(y[y.size()-1] > fluortarget)
    {
        delay(10); // Wait until we've dropped enough.
    }
}